### PR TITLE
Getting basic doxygen documentation build working

### PR DESCRIPTION
**Pull request by edhartnett**

### CODE REVIEW

**Comment by edhartnett** [comment]
@jmrosinski this PR adds a basic doxygen documentation build. Configure with --enable-docs, and then make all will build the documentation in the docs directory. (Use your browser to open docs/html/index.html).

Once we get this cleaned up a bit we can use githubs gh-pages feature to put the docs on-line. I would like to merge this so I can lock these changes in and continue trying to develop the docs.

**Comment by edhartnett** [comment]
OK, I have doxygen documented one function to show how it should be done:

```
     ! Get the wall clock time.
     !
     ! @param name Name of ???
     ! @param t time?
     ! @param value some value.
     ! @return what?
     ! @author Jim Rosinski
     integer function gptlget_wallclock (name, t, value)

```

Note that the function must have at least a one-sentence description at the start. All parameters must be documented with 
`@param param_name Some description of this parameter.
`
Note the return tag, which should describe what is returned by the function.

There are many ways we can customize the output, so if the documentation is not to your immediate taste, we can incrementally get there. The font and general look are doxygen standard, but a style-sheet may be added to change the look in every possible way.

@jmrosinski your task is now to add the documentation to the code. ;-)

**Comment by edhartnett** [comment]
@jmrosinski please decide if you want this or not. If not, I will close the PR.

**Comment by jmrosinski** [comment]
Let's leave it open. I do need to decide how to handle documentation. What's there as web pages is out of date, and doxygen seems an easier way to maintain things.

**Comment by edhartnett** [comment]
I encourage you to examine doxygen as a documentation solution.

Meanwhile I will close this PR because it is showing up in my list. When you wish to examine doxygen you can start with a current master and apply these changes if they seem helpful.

**Pull request closed without merging**
